version: "3"

services:
  aws-s3:
    image: localstack/localstack:latest
    ports:
      - "4563-4594:4563-4594"
    environment:
      - SERVICES=s3

  s3-provision:
    build: docker/s3-provision
    depends_on:
      - aws-s3
    environment:
      - S3_CORPORATE_BUCKET
      - S3_PUBLISHED_BUCKET
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION

  corporate-ingestion:
    build: docker/apache-spark/.
    depends_on:
      - spark-master
    volumes:
      - ./apps:/opt/spark-apps
      - ./steps/process_corporate_data:/app
    environment:
      - SPARK_WORKLOAD=submit
      - S3_CORPORATE_BUCKET
      - S3_PUBLISHED_BUCKET
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - LOCALSTACK
      - CORPORATE_DATA_INGESTION_LOG_LEVEL

  spark-master:
    build: docker/apache-spark/.
    ports:
      - "9090:8080"
      - "7077:7077"
    environment:
      - SPARK_WORKLOAD=master
      - SPARK_LOCAL_IP=spark-master

  spark-worker-a:
    build: docker/apache-spark/.
    ports:
      - "9091:8080"
      - "7000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_WORKLOAD=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
      - ./apps:/opt/spark-apps

  spark-worker-b:
    build: docker/apache-spark/.
    ports:
      - "9092:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_WORKLOAD=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_LOCAL_IP=spark-worker-b
    volumes:
      - ./apps:/opt/spark-apps
