jobs:
  - name: dataworks-aws-corporate-data-ingestion-production
    max_in_flight: 1
    plan:
      - in_parallel:
          - put: meta
            resource: meta-production
          - get: dataworks-aws-corporate-data-ingestion
            trigger: true
            passed:
              - dataworks-aws-corporate-data-ingestion-preprod
          - get: emr-launcher-release
            trigger: true
            passed:
              - dataworks-aws-corporate-data-ingestion-preprod
          - get: emr-relauncher-release
            trigger: true
            passed:
              - dataworks-aws-corporate-data-ingestion-preprod
          - get: al2-emr-ami
            trigger: true
            passed:
              - dataworks-aws-corporate-data-ingestion-preprod
      - .: (( inject meta.plan.terraform-bootstrap ))
        config:
          params:
            AWS_ACC: ((aws_account.production))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: production
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: production
