jobs:
  - name: dataworks-aws-corporate-data-ingestion-preprod
    max_in_flight: 1
    plan:
      - in_parallel:
          - put: meta
            resource: meta-preprod
          - get: dataworks-aws-corporate-data-ingestion
            trigger: true
            passed:
              - dataworks-aws-corporate-data-ingestion-qa
          - get: emr-launcher-release
            version: { tag: ((emr-launcher-version.preprod)) }
            trigger: true
            passed:
              - dataworks-aws-corporate-data-ingestion-qa
          - get: emr-relauncher-release
            version: { tag: ((emr-relauncher-version.preprod)) }
            trigger: true
            passed:
              - dataworks-aws-corporate-data-ingestion-qa
          - get: al2-emr-ami
            trigger: true
            passed:
              - dataworks-aws-corporate-data-ingestion-qa
      - .: (( inject meta.plan.terraform-bootstrap ))
        config:
          params:
            AWS_ACC: ((aws_account.preprod))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: preprod
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: preprod
      - .: (( inject meta.plan.rotate-corporate-data-ingestion-writer-password ))
        config:
          params:
            AWS_ACC: ((aws_account.preprod))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
