jobs:
  - name: dataworks-aws-corporate-data-ingestion-dev
    max_in_flight: 1
    plan:
      - in_parallel:
          - put: meta
            resource: meta-development
          - get: dataworks-aws-corporate-data-ingestion
            trigger: true
          - get: emr-launcher-release
            version: { tag: ((emr-launcher-version.development)) }
            trigger: true
          - get: emr-relauncher-release
            version: { tag: ((emr-relauncher-version.development)) }
            trigger: true
          - get: dataworks-behavioural-framework
            trigger: false
          - get: al2-emr-ami
            trigger: true
      - .: (( inject meta.plan.terraform-bootstrap ))
        config:
          params:
            AWS_ACC: ((aws_account.development))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: default
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: default
      - .: (( inject meta.plan.e2e-tests))
        config:
          params:
            TF_WORKSPACE: default
            AWS_ACC: ((aws_account.development))
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
